# Generated by Django 3.1.7 on 2021-04-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwa firmy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_name_l',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nazwa firmy c.d.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nip_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Numer nip'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=18, verbose_name='Numer telefonu'),
        ),
    ]
