# Generated by Django 3.1.7 on 2021-04-20 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210416_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('user_id', '-id'), 'verbose_name_plural': 'Adresy'},
        ),
    ]
