# Generated by Django 3.1.7 on 2021-04-23 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20210420_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='main',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=64, verbose_name='Miasto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default=1, max_length=128, verbose_name='Ulica'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
