# Generated by Django 3.1.7 on 2021-04-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=13, verbose_name='Nazwa strony')),
                ('description', models.CharField(max_length=156, verbose_name='Meta description')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'Strony/Zakładki',
                'ordering': ('name',),
            },
        ),
    ]
