# Generated by Django 3.2 on 2021-04-06 18:53

from django.db import migrations, models
import django_resized.forms
import front.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, size=[1280, 960], upload_to='images/', validators=[front.models.file_size])),
                ('carousel_images', models.BooleanField(default=False, verbose_name='Zjęcie dla karulseli?')),
            ],
            options={
                'verbose_name_plural': 'Galeria',
                'ordering': ('-id', 'image'),
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=13, verbose_name='Nazwa strony')),
                ('description', models.CharField(max_length=156, verbose_name='Meta description')),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
            ],
            options={
                'verbose_name_plural': 'Strony/Zakładki',
                'ordering': ('name',),
            },
        ),
    ]
