# Generated by Django 3.1.7 on 2021-04-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20210404_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
