# Generated by Django 3.1.7 on 2021-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
