# Generated by Django 3.1.7 on 2021-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymethod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcopy',
            name='color_text',
            field=models.IntegerField(choices=[(1, 'Czarne'), (2, 'Czerwone'), (3, 'Niebieskie'), (4, 'Zielone'), (5, 'Fioletowe')], verbose_name='Kolor odbicia'),
        ),
        migrations.AlterField(
            model_name='productcopy',
            name='qty',
            field=models.IntegerField(verbose_name='Ilość pozycji'),
        ),
    ]
