# Generated by Django 3.1.7 on 2021-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210412_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcopy',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Rabat'),
        ),
        migrations.AddField(
            model_name='productcopy',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Informacje'),
        ),
    ]
