# Generated by Django 3.1.7 on 2021-04-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210412_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcopy',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='productcopy',
            old_name='product',
            new_name='product_id',
        ),
    ]
