# Generated by Django 3.2 on 2021-04-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210410_0825'),
        ('orders', '0004_auto_20210412_1232'),
    ]

    operations = [
    ]
