# Generated by Django 3.2 on 2021-04-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_0002_auto_20210410_0825_0004_auto_20210412_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcopy',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Pozycje rachunku'},
        ),
        migrations.AlterField(
            model_name='productcopy',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='Relacja do zamówienia'),
        ),
    ]
