# Generated by Django 3.1.7 on 2021-04-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_deliverymethod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Czy domyślny?'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Czy aktualna?'),
        ),
    ]
