# Generated by Django 3.2 on 2021-04-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210413_1755'),
        ('orders', '0010_auto_20210414_1639'),
    ]

    operations = [
    ]
