# Generated by Django 3.1.7 on 2021-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_merge_0006_auto_20210413_1755_0010_auto_20210414_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AlterField(
            model_name='orders',
            name='type_of_order',
            field=models.CharField(max_length=64, verbose_name='Rodzaj dostawy'),
        ),
    ]
