# Generated by Django 3.1.7 on 2021-04-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210420_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='inpost_box',
            field=models.BooleanField(default=True, verbose_name='Czy dostawa to paczkomat?'),
        ),
    ]
