# Generated by Django 3.1.7 on 2021-04-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_deliverymethod_inpost_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='inpost_box',
            field=models.BooleanField(default=False, verbose_name='Czy dostawa to paczkomat?'),
        ),
    ]
