# Generated by Django 3.1.7 on 2021-04-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternatywny text dla obrazka'),
        ),
        migrations.AddField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title dla obrazka'),
        ),
        migrations.AddField(
            model_name='category',
            name='alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternatywny text dla obrazka'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title dla obrazka'),
        ),
        migrations.AddField(
            model_name='images',
            name='alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternatywny text dla obrazka'),
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title dla obrazka'),
        ),
        migrations.AddField(
            model_name='products',
            name='alt',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Alternatywny text dla obrazka'),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title dla obrazka'),
        ),
    ]
