# Generated by Django 3.1.7 on 2021-04-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('number', 'name'), 'verbose_name_plural': 'Kategorie produktów'},
        ),
        migrations.AddField(
            model_name='category',
            name='tag_desc',
            field=models.CharField(default=1, max_length=156, verbose_name='Meta description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='tag_title',
            field=models.CharField(default=1, max_length=70, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(default=1, max_length=128, verbose_name='Opis kategorii'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa kategorii'),
        ),
    ]
