# Generated by Django 3.1.7 on 2021-04-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210407_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Brand info'),
        ),
    ]
