# Generated by Django 3.1.7 on 2021-04-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210406_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='on_page',
            field=models.BooleanField(default=False, verbose_name='Czy na pierwszej stronie?'),
        ),
    ]
