# Generated by Django 3.1.7 on 2021-04-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa coloru')),
                ('class_text', models.CharField(max_length=32, verbose_name='Text dla koloru klasay')),
            ],
            options={
                'verbose_name_plural': 'Colory',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='products',
            name='price_promo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Cena promocyjna'),
        ),
        migrations.AlterField(
            model_name='products',
            name='alt',
            field=models.CharField(default=1, max_length=125, verbose_name='Alternatywny text dla obrazka'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price_netto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Cena netto'),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.colors', verbose_name='Kolor produktu'),
        ),
    ]
