# Generated by Django 3.1.7 on 2021-04-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210409_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'ordering': ('name',), 'verbose_name_plural': 'Kolory'},
        ),
        migrations.AddField(
            model_name='colors',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, verbose_name='Slug'),
        ),
    ]
