# Generated by Django 3.1.7 on 2021-04-06 11:57

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_on_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, size=[1280, 960], upload_to='images/', validators=[products.models.file_size])),
                ('main', models.BooleanField(default=False, verbose_name='Zdjęcie główne')),
                ('stamp', models.BooleanField(default=False, verbose_name='Zdjęcie wzornika?')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='products.products', verbose_name='Zdjęcie produktu')),
            ],
            options={
                'verbose_name_plural': 'Galeria',
                'ordering': ('-id', 'image'),
            },
        ),
    ]
