# Generated by Django 3.1.7 on 2021-04-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210409_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='store_id',
            new_name='store',
        ),
    ]
