# Generated by Django 3.1.7 on 2021-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='door',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numer lokalu'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa magazynu'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(max_length=32, verbose_name='Telefon kontaktowy do magazynu'),
        ),
    ]
