# Generated by Django 3.1.7 on 2021-04-06 12:13

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210406_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nazwa marki')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, size=[1280, 960], upload_to='images/categorys/', validators=[products.models.file_size], verbose_name='Zdjęcie główne')),
            ],
            options={
                'verbose_name_plural': 'Marka produktów',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Podkategoria produktu'),
        ),
    ]
