# Generated by Django 3.1.7 on 2021-04-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210412_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='class_text',
            field=models.CharField(max_length=32, verbose_name='Text dla koloru klasy'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Nazwa koloru'),
        ),
    ]
