# Generated by Django 3.1.7 on 2021-04-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210406_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_netto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Cena podstawowa'),
        ),
    ]
